load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "gguf",
    srcs = ["gguf_loader.cc"],
    hdrs = ["gguf_loader.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//engine/tensor",
    ],
)

cc_test(
    name = "gguf_loader_test",
    srcs = ["gguf_loader_test.cc"],
    deps = [
        ":gguf",
        "@googletest//:gtest_main",
    ],
)
