load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "tokenizer",
    srcs = [
        "bpe_tokenizer.cc",
    ],
    hdrs = [
        "bpe_tokenizer.h",
        "tokenizer.h",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "bpe_tokenizer_test",
    srcs = ["bpe_tokenizer_test.cc"],
    deps = [
        ":tokenizer",
        "@googletest//:gtest_main",
    ],
)
