load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "ops",
    srcs = ["ops.cc"],
    hdrs = ["ops.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//engine/tensor",
    ],
)

cc_test(
    name = "ops_test",
    srcs = ["ops_test.cc"],
    deps = [
        ":ops",
        "@googletest//:gtest_main",
    ],
)
