load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "attention",
    srcs = [
        "flash_attention.cc",
        "kv_cache.cc",
    ],
    hdrs = [
        "flash_attention.h",
        "kv_cache.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//engine/tensor",
    ],
)

cc_test(
    name = "kv_cache_test",
    srcs = ["kv_cache_test.cc"],
    deps = [
        ":attention",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "flash_attention_test",
    srcs = ["flash_attention_test.cc"],
    deps = [
        ":attention",
        "//engine/ops",
        "//engine/tensor",
        "@googletest//:gtest_main",
    ],
)
